steps:
  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/hobsleepr/reservations/production'
      - '-f'
      - 'apps/reservations/Dockerfile'
      - '.'
  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-central2-docker.pkg.dev/hobsleepr/reservations/production'

  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/hobsleepr/auth/production'
      - '-f'
      - 'apps/auth/Dockerfile'
      - '.'
  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-central2-docker.pkg.dev/hobsleepr/auth/production'

  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/hobsleepr/notifications/production'
      - '-f'
      - 'apps/notifications/Dockerfile'
      - '.'
  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-central2-docker.pkg.dev/hobsleepr/notifications/production'

  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/hobsleepr/payments/production'
      - '-f'
      - 'apps/payments/Dockerfile'
      - '.'
  - name: 'grc.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-central2-docker.pkg.dev/hobsleepr/payments/production'
