services:
  reservations:
    build:
      context: .
      target: development
      dockerfile: ./apps/reservations/Dockerfile
    command: pnpm run start:dev reservations
    env_file: ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      target: development
      dockerfile: ./apps/auth/Dockerfile
    command: pnpm run start:dev auth
    env_file: ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      target: development
      dockerfile: ./apps/payments/Dockerfile
    command: pnpm run start:dev payments
    env_file: ./apps/payments/.env
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      target: development
      dockerfile: ./apps/notifications/Dockerfile
    command: pnpm run start:dev notifications
    env_file: ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
