apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/hobsleepr/payments/production
        name: payments
        ports:
          - containerPort: 3003
        env:
          - name: API_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: strip-secret
                key: apiKey
          - name: TCP_PORT
            value: '3003'
          - name: NOTIFICATIONS_PORT
            value: '3004'
          - name: NOTIFICATIONS_HOST
            value: notifications

