apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/hobsleepr/reservations/production
        name: reservations
        ports:
          - containerPort: 3000
        env:
          - name: PORT
            value: '3000'
          - name: AUTH_PORT
            value: '3002'
          - name: AUTH_HOST
            value: auth-tcp
          - name: PAYMENTS_PORT
            value: '3003'
          - name: PAYMENTS_HOST
            value: payments
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString

